# @summary Represents a ProxySQL query rule.
type Proxysql::Rule = Array[Hash[String, Struct[{ rule_id                         => Integer,
  active                          => Integer,
  Optional[username]              => String[1],
  Optional[schemaname]            => String[1],
  Optional[flag_in]               => Integer,
  Optional[flag_out]              => Integer,
  Optional['apply']               => Integer,
  Optional[client_addr]           => String[1],
  Optional[proxy_addr]            => String[1],
  Optional[proxy_port]            => Integer,
  Optional[digest]                => String[1],
  Optional[match_digest]          => String[1],
  Optional[match_pattern]         => String[1],
  Optional[replace_pattern]       => String[1],
  Optional[negate_match_pattern]  => Integer[0,1],
  Optional[destination_hostgroup] => Integer,
  Optional[cache_ttl]             => Integer,
  Optional[reconnect]             => Integer[0,1],
  Optional[timeout]               => Integer,
  Optional[retries]               => Integer,
  Optional[delay]                 => Integer,
  Optional[error_msg]             => String[1],
  Optional[log]                   => Integer[0,1],
  Optional[mirror_hostgroup]      => Integer,
Optional[mirror_flag_out]       => Integer, }],1,1]]
